export const BOTSWANA_DISTRICTS = [
  "Central District",
  "Chobe District",
  "Ghanzi District",
  "Kgalagadi District",
  "Kgatleng District",
  "Kweneng District",
  "North East District",
  "North West District",
  "South East District",
  "Southern District",
] as const

export const BOTSWANA_COUNCILS = [
  "Gaborone City Council",
  "Francistown City Council",
  "Lobatse Town Council",
  "Selebi Phikwe Town Council",
  "Jwaneng Town Council",
  "SOWA Town Council",
  "Bobirwa District Council",
  "Boteti District Council",
  "Charleshill District Council",
  "Chobe District Council",
  "Ghanzi District Council",
  "Goodhope District Council",
  "Hukuntsi District Council",
  "Kanye District Council",
  "Kgatleng District Council",
  "Kweneng District Council",
  "Letlhakeng District Council",
  "Mabutsane District Council",
  "Mahalapye District Council",
  "Mogoditshane-Thamaga District Council",
  "Moshupa District Council",
  "North East District Council",
  "North West District Council",
  "Okavango District Council",
  "Palapye District Council",
  "Ramotswa District Council",
  "Serowe District Council",
  "Tlokweng District Council",
  "Tonota District Council",
  "Tsabong District Council",
  "Tutume District Council",
] as const
